name: GO

on:
  push:
    branches:
      - main # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t go-app:${{ github.sha }} .
          docker tag go-app:${{ github.sha }} ${{ vars.REGISTRY }}:latest

      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: crpi-acswnartdy7xwulu.cn-guangzhou.personal.cr.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ vars.REGISTRY }}:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ vars.REGISTRY }}:latest
            docker stop go-app || true  
            docker rm go-app || true   
            docker run -d --name go-app -p 8081:8081 ${{ vars.REGISTRY }}:latest
