name: GO

on:
  push:
    branches:
      - main # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t historylizhi/go-app:${{ github.sha }} .
          docker tag historylizhi/go-app:${{ github.sha }} username/go-app:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: historylizhi
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push historylizhi/go-app:latest
          docker push historylizhi/go-app:${{ github.sha }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{secrets.SSH_KEY}}
          script: |
            docker pull username/go-app:${{ github.sha }}
            docker stop go-app || true  
            docker rm go-app || true   
            docker run -d --name go-app -p 8081:8081 username/go-app:${{ github.sha }}
